# Generated by Django 3.2.6 on 2021-08-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_base_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitor',
            name='unit',
            field=models.CharField(choices=[('pF', 'pF'), ('nF', 'nF'), ('mkF', 'mkF')], max_length=5),
        ),
        migrations.AlterField(
            model_name='chip',
            name='microcircuit_type',
            field=models.CharField(choices=[('analog', 'analog'), ('digital', 'digital')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transistor',
            name='junction_type',
            field=models.CharField(choices=[('pnp', 'pnp'), ('npn', 'npn')], max_length=5),
        ),
    ]
